from projects.Kofile.Lib.test_parent import ApiTestParent
from runner import run_test

description = """
"""

tags = ['API']


class test(ApiTestParent):                                                                                # noqa
    oit = 'REAL PROPERTY'

    def __init__(self, data):
        super(test, self).__init__(data, __name__)

    @property
    def schema(self):
        return {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "Id": {"type": "number"},
                    "Code": {"type": ["string", "null"]},
                    "ConfigId": {"type": ["string", "null"]},
                    "Name": {"type": "string", "value": self.oit},
                    "InternetAttachmentsAccess": {"type": "boolean", "value": False},
                    "IntranetAttachmentsAccess": {"type": "boolean", "value": False},
                    "IsConsolidationEnabled": {"type": "boolean", "value": False},
                    "IsAutoGenerated": {"type": "boolean", "value": True},
                }
            }
        }

    def __test__(self):
        params = (('term', self.oit),)
        self.response = self.session.get(self.get_url(self.api_urls.GetDocumentGroupNumber), params=params)
        assert self.response.status_code == 200, f"Actual response status: {self.response.status_code}"
        self.validate(instance=self.response.json(), schema=self.schema)


if __name__ == '__main__':
    run_test(__file__, browser="none")
